<?php
// Shared helpers for the subtitle-track HLS scripts (subtitle_track_playlist.php,
// subtitle_video_playlist.php).

// Confirmed directly against a real debrid-resolved link (Premiumize):
// requesting the SAME movie again after roughly 10-20 minutes returns a
// DIFFERENT signed CDN URL - different domain-pool prefix, different
// signature/auth token in the path - but the exact same filename at the
// end. That's expected (a legitimate, time-limited access token, not a
// bug), but it means any cache keyed on the FULL video URL (duration,
// keyframe list, seek-reliability - none of which actually depend on which
// specific URL currently happens to point at this file, only on the file's
// own content) goes cold and has to be fully re-probed every time the link
// refreshes, even though nothing about the underlying file changed. On a
// keyframe probe that costs 30-40s, that's the difference between "warms
// up once and stays warm" and "effectively never gets to stay warm for a
// popular title that keeps getting re-requested across link refreshes."
//
// The filename is the one part of these URLs confirmed stable across a
// resolve-again cycle, so it's what every content-identity cache uses as
// its key instead of the full URL - deliberately NOT the whole path (the
// per-request auth segments in there are exactly what's volatile) and NOT
// just relying on the caller to strip it themselves, so every cache in this
// file gets this fix uniformly rather than one at a time.
function stableCacheKeyForVideo($videoUrl) {
    $path = parse_url($videoUrl, PHP_URL_PATH);
    if ($path === null || $path === false || $path === '') {
        return $videoUrl;
    }
    $filename = urldecode(basename($path));
    return $filename !== '' ? $filename : $videoUrl;
}

// Splits the byte stream from ffmpeg's fragmented-MP4 muxer
// (-movflags frag_keyframe+empty_moov+delay_moov+default_base_moof) into
// the leading init segment (ftyp+moov: the codec/track setup every fragment
// needs to be decodable) and everything from the first 'moof' box onward
// (the actual media: one or more moof+mdat pairs, since frag_keyframe opens
// a new fragment at every keyframe, plus a trailing mfra index - all of
// which get treated as one opaque blob here, since we only need to find
// where the fragment data starts, not parse inside it).
//
// MP4 boxes are plain TLV - a 4-byte big-endian size then a 4-byte ASCII
// type - so walking them to find that one boundary needs no real MP4
// parsing library.
function splitFmp4InitAndFragment($bytes) {
    $offset = 0;
    $len = strlen($bytes);

    while ($offset + 8 <= $len) {
        $size = unpack('N', substr($bytes, $offset, 4))[1];
        $type = substr($bytes, $offset + 4, 4);

        if ($type === 'moof') {
            return [substr($bytes, 0, $offset), substr($bytes, $offset)];
        }

        $boxHeaderLen = 8;
        if ($size === 1) {
            // 64-bit "largesize" extension - real size is in the next 8 bytes.
            if ($offset + 16 > $len) {
                break;
            }
            $high = unpack('N', substr($bytes, $offset + 8, 4))[1];
            $low = unpack('N', substr($bytes, $offset + 12, 4))[1];
            $size = ($high << 32) | $low;
            $boxHeaderLen = 16;
        } elseif ($size === 0) {
            // "Extends to end of file" - not something ffmpeg emits here;
            // bail rather than risk an infinite loop.
            break;
        }

        if ($size < $boxHeaderLen || $offset + $size > $len) {
            // Malformed/truncated box (e.g. buffer ends mid-box while still
            // accumulating) - stop and let the caller decide what to do
            // with a not-yet-complete buffer.
            break;
        }

        $offset += $size;
    }

    // No 'moof' found yet - treat everything as (incomplete) init data.
    return [$bytes, ''];
}

// Each segment is generated by its own independent ffmpeg process, so its
// internal 'mfhd' (movie fragment header) sequence_number always restarts
// at 1 - ffmpeg has no way to know it's producing segment 6 of a movie
// rather than segment 1 of a fresh file. A real HLS/CMAF demuxer expects
// this number to keep incrementing across fragments of the same track and
// logs a discontinuity every time it doesn't (confirmed directly in a real
// player's debug log: "Fragment sequence discontinuity detected 1 != 2" on
// nearly every segment). Since the true segment index is always derivable
// from $start (fixed-length segments), patching it here costs nothing and
// makes the output match what a real continuous CMAF encoder would have
// produced. frag_keyframe can open more than one internal fragment per
// segment, so every 'moof' in the buffer gets its own consecutive number,
// not just the first.
function patchFragmentSequenceNumbers(&$fragmentBytes, $startSequenceNumber) {
    $offset = 0;
    $len = strlen($fragmentBytes);
    $seq = $startSequenceNumber;

    while ($offset + 8 <= $len) {
        $size = unpack('N', substr($fragmentBytes, $offset, 4))[1];
        $type = substr($fragmentBytes, $offset + 4, 4);

        if ($size < 8 || $offset + $size > $len) {
            break;
        }

        if ($type === 'moof') {
            // mfhd is always moof's first child box: 8-byte moof header,
            // then mfhd's own 8-byte header, then 4-byte version/flags,
            // then the 4-byte sequence_number this patches.
            $mfhdOffset = $offset + 8;
            if ($mfhdOffset + 16 <= $len && substr($fragmentBytes, $mfhdOffset + 4, 4) === 'mfhd') {
                $seqFieldOffset = $mfhdOffset + 12;
                overwriteBytes($fragmentBytes, $seqFieldOffset, pack('N', $seq));
                $seq++;
            }
        }

        $offset += $size;
    }
}

// Finds every top-level box of $type within [$start, $end) of $bytes -
// shared plain-TLV walker used by patchAllFragmentTfdts() to locate however
// many 'moof' boxes (and their 'traf'/'tfhd'/'tfdt'/'trun' children) a
// fragment actually contains, instead of assuming exactly one.
function findChildBoxes($bytes, $type, $start, $end) {
    $offset = $start;
    $found = [];
    while ($offset + 8 <= $end) {
        $size = unpack('N', substr($bytes, $offset, 4))[1];
        $boxType = substr($bytes, $offset + 4, 4);
        if ($size < 8 || $offset + $size > $end) {
            break;
        }
        if ($boxType === $type) {
            $found[] = [$offset, $size];
        }
        $offset += $size;
    }
    return $found;
}

// Reads a tfhd box's default_sample_duration field, if present (flags bit
// 0x000008) - null if the box doesn't carry one (e.g. per-sample durations
// are used instead - see readTrunTotalDuration()).
function readTfhdDefaultSampleDuration($bytes, $tfhdOffset) {
    $flags = unpack('N', "\x00" . substr($bytes, $tfhdOffset + 9, 3))[1];
    if (!($flags & 0x000008)) {
        return null;
    }
    $fieldOffset = $tfhdOffset + 8 + 4 + 4; // header(8) + version/flags(4) + track_ID(4)
    if ($flags & 0x000001) { // base-data-offset-present
        $fieldOffset += 8;
    }
    if ($flags & 0x000002) { // sample-description-index-present
        $fieldOffset += 4;
    }
    return unpack('N', substr($bytes, $fieldOffset, 4))[1];
}

// Computes one trun's total duration in the track's timescale - either by
// summing real per-sample durations (when trun's own sample-duration-present
// flag is set) or, the more common case confirmed on real ffmpeg output,
// sample_count * tfhd's default_sample_duration (trun carries no duration
// field of its own at all - every sample implicitly uses the tfhd default).
// Returns null if neither source is available - the caller must not assume
// a duration in that case rather than silently defaulting to 0, which would
// make every subsequent fragment's patched tfdt wrong instead of just this
// one being left unpatched.
function readTrunTotalDuration($bytes, $trunOffset, $defaultSampleDuration) {
    $flags = unpack('N', "\x00" . substr($bytes, $trunOffset + 9, 3))[1];
    $sampleCount = unpack('N', substr($bytes, $trunOffset + 12, 4))[1];

    if (!($flags & 0x000100)) { // no per-sample duration field
        if ($defaultSampleDuration === null) {
            return null;
        }
        return $sampleCount * $defaultSampleDuration;
    }

    // Per-sample durations ARE present - each sample entry's byte size
    // depends on which of the other optional fields trun also carries, so
    // the duration field's position within each entry has to be computed
    // the same way, not assumed to be first.
    $entryOffset = $trunOffset + 16; // header + version/flags(4) + sample_count(4) + [data_offset(4)] + [first_sample_flags(4)]
    if ($flags & 0x000001) {
        $entryOffset += 4;
    }
    if ($flags & 0x000004) {
        $entryOffset += 4;
    }

    $entrySize = 4; // sample_duration itself
    if ($flags & 0x000200) {
        $entrySize += 4;
    }
    if ($flags & 0x000400) {
        $entrySize += 4;
    }
    if ($flags & 0x000800) {
        $entrySize += 4;
    }

    $total = 0;
    for ($i = 0; $i < $sampleCount; $i++) {
        $total += unpack('N', substr($bytes, $entryOffset + $i * $entrySize, 4))[1];
    }
    return $total;
}

// Writes $replacement over $bytes at $offset, mutating the existing string.
//
// substr_replace() returns a NEW string, i.e. a full copy of the whole
// fragment for every single box patched. On a high-bitrate source that is
// tens of megabytes per copy, and enough of them exhausted PHP's 128M
// memory_limit outright - confirmed on a real 4K segment, which died with
// "Allowed memory size of 134217728 bytes exhausted (tried to allocate
// 34007786 bytes)" inside writeTfdtValue(). Because error_reporting is off
// in the segment scripts, that fatal was completely invisible: the client
// just got an empty 200, saw a missing segment, and logged a timestamp
// discontinuity across the gap. Per-byte assignment keeps patching
// proportional to the handful of bytes actually changed.
function overwriteBytes(&$bytes, $offset, $replacement) {
    $length = strlen($replacement);
    for ($i = 0; $i < $length; $i++) {
        $bytes[$offset + $i] = $replacement[$i];
    }
}

// Overwrites one tfdt box's base_media_decode_time, handling both the
// 32-bit (version 0) and 64-bit (version 1) forms - ffmpeg's muxer uses
// version 1 whenever the value wouldn't fit in 32 bits.
function writeTfdtValue(&$bytes, $tfdtOffset, $value) {
    $version = ord($bytes[$tfdtOffset + 8]);
    $valueOffset = $tfdtOffset + 12;
    if ($version === 1) {
        $packed = pack('NN', ($value >> 32) & 0xFFFFFFFF, $value & 0xFFFFFFFF);
    } else {
        $packed = pack('N', $value & 0xFFFFFFFF);
    }
    overwriteBytes($bytes, $valueOffset, $packed);
}

// Confirmed directly (box-walked several independently generated segments,
// on two unrelated sources - one x265/TrueHD, one x264/AAC): when ffmpeg is
// run with -copyts and a non-zero -ss, every fragment's own internal sample
// timing (trun) correctly reflects the real seek position, but 'tfdt'
// (base_media_decode_time) is NOT reliably absolute anywhere in the buffer -
// an ffmpeg fragmented-MP4 muxer bug, not anything specific to this
// project's encode settings. What was originally assumed ("only the FIRST
// internal moof needs patching, later ones are already correct") turned out
// to be wrong on further testing: frag_keyframe can split a single segment
// into MULTIPLE internal moof fragments (confirmed: a real segment,
// requested as one 8-10s window, came back as a 249-sample fragment
// followed by a second, separate 2-sample one), and that SECOND fragment's
// tfdt was ALSO wrong - not zero this time, but a value that looked exactly
// like a fragment-relative offset (matching the segment's own total
// requested length) rather than the real absolute time. A real CMAF/HLS
// demuxer trusts tfdt as authoritative for where EVERY fragment starts, so
// getting even one internal fragment wrong reintroduces exactly the same
// class of discontinuity this patch exists to prevent - manifesting as the
// video appearing to speed up/slow down or drift out of sync with audio
// rather than a hard stall, since by the time this second, smaller
// fragment's bad timestamp hit, most of the segment's content had already
// played back correctly.
//
// The fix: patch EVERY internal moof's tfdt, chaining forward from the one
// externally-confirmed correct value ($firstFragmentBaseTime, from
// extractRealFragmentStartPtsTime()) - each subsequent fragment's tfdt is
// computed as the previous fragment's (now-correct) tfdt plus that
// fragment's own real total duration (see readTrunTotalDuration()), instead
// of trusting whatever ffmpeg itself wrote there.
function patchAllFragmentTfdts(&$fragmentBytes, $firstFragmentBaseTime) {
    $len = strlen($fragmentBytes);
    $moofs = findChildBoxes($fragmentBytes, 'moof', 0, $len);
    if (empty($moofs)) {
        return;
    }

    $nextBaseTime = $firstFragmentBaseTime;

    foreach ($moofs as [$moofOffset, $moofSize]) {
        $trafs = findChildBoxes($fragmentBytes, 'traf', $moofOffset + 8, $moofOffset + $moofSize);
        if (empty($trafs)) {
            continue;
        }
        [$trafOffset, $trafSize] = $trafs[0];
        $trafEnd = $trafOffset + $trafSize;

        $tfdts = findChildBoxes($fragmentBytes, 'tfdt', $trafOffset + 8, $trafEnd);
        if (empty($tfdts)) {
            continue;
        }
        [$tfdtOffset] = $tfdts[0];

        writeTfdtValue($fragmentBytes, $tfdtOffset, (int) round($nextBaseTime));

        // Only worth computing if there's a NEXT fragment to chain onto -
        // and only possible to trust if this fragment's own duration can
        // actually be determined (see readTrunTotalDuration()'s null case).
        $defaultSampleDuration = null;
        $tfhds = findChildBoxes($fragmentBytes, 'tfhd', $trafOffset + 8, $trafEnd);
        if (!empty($tfhds)) {
            [$tfhdOffset] = $tfhds[0];
            $defaultSampleDuration = readTfhdDefaultSampleDuration($fragmentBytes, $tfhdOffset);
        }

        $truns = findChildBoxes($fragmentBytes, 'trun', $trafOffset + 8, $trafEnd);
        if (!empty($truns)) {
            [$trunOffset] = $truns[0];
            $duration = readTrunTotalDuration($fragmentBytes, $trunOffset, $defaultSampleDuration);
            if ($duration !== null) {
                $nextBaseTime += $duration;
            }
        }
    }
}

// Total decode duration of one moof's track fragment, in the fragment's own
// timescale - null when the trun can't be read (see readTrunTotalDuration()).
function readFragmentDuration($bytes, $moofOffset, $moofSize) {
    $trafs = findChildBoxes($bytes, 'traf', $moofOffset + 8, $moofOffset + $moofSize);
    if (empty($trafs)) {
        return null;
    }
    [$trafOffset, $trafSize] = $trafs[0];
    $trafEnd = $trafOffset + $trafSize;

    $defaultSampleDuration = null;
    $tfhds = findChildBoxes($bytes, 'tfhd', $trafOffset + 8, $trafEnd);
    if (!empty($tfhds)) {
        $defaultSampleDuration = readTfhdDefaultSampleDuration($bytes, $tfhds[0][0]);
    }

    $truns = findChildBoxes($bytes, 'trun', $trafOffset + 8, $trafEnd);
    if (empty($truns)) {
        return null;
    }
    return readTrunTotalDuration($bytes, $truns[0][0], $defaultSampleDuration);
}

// Drops the trailing fragment(s) that actually belong to the NEXT segment.
//
// ffmpeg applies -to in DECODE order and stops only once a packet crosses
// it, so a stream copy always runs slightly past the requested end - and by
// then frag_keyframe has already opened a new fragment at the keyframe the
// next segment will start from. Every segment therefore shipped a short
// trailing fragment holding its successor's first frames. Confirmed by
// probing four consecutive real segments: each one's last 2-5 samples were
// exactly the next one's first samples (e.g. segment 0 ended at pts 9.259
// while segment 1 began at 9.175). Decoders see the same pictures twice
// ("Duplicate POC in a sequence", then "Could not find ref with POC" once
// the reference lists diverge), and patchAllFragmentTfdts() had to stretch
// each segment's timeline to cover the extra samples - which is what
// surfaced as a timestamp discontinuity at every single segment boundary.
//
// A fragment that genuinely belongs to this segment always ENDS at or before
// the segment's declared end; the duplicate one straddles that end, since it
// starts at the successor's keyframe and runs until ffmpeg's cutoff stops
// it. Testing the END is what separates it from a legitimate interior
// fragment - frag_keyframe splits on EVERY keyframe, so a segment spanning
// several of them has interior fragments that must be kept (confirmed: one
// 3.2s segment came back as 47 + 32 real samples plus a 2-sample duplicate).
//
// Fragment 0 is never dropped - an empty segment is worse than a couple of
// duplicated frames - and anything after the first overrunning fragment goes
// with it, including the trailing mfra index, which CMAF playback does not
// need.
function dropOvershootFragments(&$fragmentBytes, $maxDurationTicks) {
    $total = strlen($fragmentBytes);
    $moofs = findChildBoxes($fragmentBytes, 'moof', 0, $total);
    if (count($moofs) < 2) {
        return;
    }

    $relativeStart = 0;
    foreach ($moofs as $index => [$moofOffset, $moofSize]) {
        $duration = readFragmentDuration($fragmentBytes, $moofOffset, $moofSize);
        if ($duration === null) {
            return;
        }
        if ($index > 0 && $relativeStart + $duration > $maxDurationTicks) {
            $fragmentBytes = substr($fragmentBytes, 0, $moofOffset);
            return;
        }
        $relativeStart += $duration;
    }
}

// Maps a short request language code ('en', 'fr', ...) to every ISO-639
// spelling ffprobe might report for it. Matroska tags are usually 3-letter
// bibliographic codes ('fre', 'ger'), MP4 often carries the terminological
// ones ('fra', 'deu'), and some remuxes just use the 2-letter form.
function audioLanguageAliases($langCode) {
    $aliases = [
        'en' => ['en', 'eng', 'english'],
        'fr' => ['fr', 'fre', 'fra', 'french', 'francais', 'français'],
        'pt' => ['pt', 'por', 'portuguese', 'portugues', 'português'],
        'es' => ['es', 'spa', 'esp', 'spanish', 'espanol', 'español'],
        'de' => ['de', 'ger', 'deu', 'german', 'deutsch'],
        'it' => ['it', 'ita', 'italian', 'italiano'],
        'ru' => ['ru', 'rus', 'russian'],
        'ja' => ['ja', 'jpn', 'japanese'],
        'ko' => ['ko', 'kor', 'korean'],
        'zh' => ['zh', 'chi', 'zho', 'chinese', 'mandarin'],
        'ar' => ['ar', 'ara', 'arabic'],
        'hi' => ['hi', 'hin', 'hindi'],
    ];
    return $aliases[strtolower($langCode)] ?? [strtolower($langCode)];
}

// Picks which audio track to actually serve, given every track the source
// carries and the language the request asked for.
//
// Blindly mapping 0:a:0 (which this used to do everywhere) serves whatever
// track the release happens to put first, and multi-audio releases routinely
// put something other than English there - confirmed by two real reports on
// the English account: The Beekeeper playing Italian and Black Widow playing
// Russian, both while the playlist advertised LANGUAGE="eng". Matching on the
// track's own language tag fixes the substitution at its source.
//
// Returns [audioIndex, resolvedLanguage]. An untagged single-track file is
// taken at face value (index 0, language unknown) - that is the common,
// perfectly normal case and there is nothing better to go on. When several
// tracks exist and NONE matches, index 0 is still returned but the caller is
// told the real language so it can at least label the track honestly instead
// of claiming a language it isn't.
function pickAudioStreamForLanguage($audioStreams, $langCode) {
    if (empty($audioStreams)) {
        return [0, ''];
    }

    $aliases = audioLanguageAliases($langCode);

    foreach ($audioStreams as $stream) {
        if (in_array($stream['language'], $aliases, true)) {
            return [$stream['audioIndex'], $stream['language']];
        }
    }

    // Nothing tagged with the requested language. A lone untagged track is
    // almost always the intended audio; several tagged ones mean this really
    // is a wrong-language file and the label must say so.
    return [0, $audioStreams[0]['language']];
}

// Searches OpenSubtitles' own REST API for European/Brazilian Portuguese
// subtitles, as a fallback for when the AIOStreams subtitle route returns
// nothing (see $openSubtitlesApiKey in config.php for when that happens).
//
// Returns entries carrying a file_id rather than a URL: turning one into a
// real downloadable link costs a request against a 20/day quota, so that
// step is deliberately deferred to openSubtitlesFetchVtt(), which only runs
// when a viewer actually opens the track.
function openSubtitlesSearchPortuguese($imdbId) {
    global $openSubtitlesApiKey;

    if (empty($openSubtitlesApiKey) || empty($imdbId)) {
        return [];
    }

    // The API wants the bare numeric id, not the "tt" form.
    $numericId = ltrim((string) $imdbId, 'tT');
    if (!ctype_digit($numericId)) {
        return [];
    }

    // languages must be percent-encoded - an unescaped comma gets a 301 to a
    // normalized URL that curl won't repeat the headers on, which reads as an
    // empty result rather than an error.
    $url = 'https://api.opensubtitles.com/api/v1/subtitles?imdb_id=' . $numericId
        . '&languages=' . rawurlencode('pt-PT,pt-BR');

    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT => 12,
        CURLOPT_HTTPHEADER => [
            'Api-Key: ' . $openSubtitlesApiKey,
            'User-Agent: tmdb-to-vod v1.0',
            'Accept: application/json',
        ],
    ]);
    $response = curl_exec($ch);
    $status = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($response === false || $status !== 200) {
        return [];
    }

    $data = json_decode($response, true);
    if (empty($data['data'])) {
        return [];
    }

    $results = [];
    foreach ($data['data'] as $item) {
        $attributes = $item['attributes'] ?? [];
        $fileId = $attributes['files'][0]['file_id'] ?? null;
        if ($fileId === null) {
            continue;
        }
        $langCode = strtolower($attributes['language'] ?? '');
        if ($langCode !== 'pt-pt' && $langCode !== 'pt-br') {
            continue;
        }
        $results[] = [
            'osFileId' => (int) $fileId,
            'name' => trim((string) ($attributes['release'] ?? 'Portuguese')) ?: 'Portuguese',
            'trusted' => !empty($attributes['from_trusted']),
            'downloads' => (int) ($attributes['download_count'] ?? 0),
            'langCode' => $langCode,
            'hlsLanguageTag' => $langCode === 'pt-br' ? 'pt-BR' : 'pt-PT',
        ];
    }

    // Most-downloaded first within each dialect - a decent proxy for "least
    // likely to be badly synced" when there is nothing else to go on.
    usort($results, function ($a, $b) {
        if ($a['trusted'] !== $b['trusted']) {
            return ($b['trusted'] ? 1 : 0) <=> ($a['trusted'] ? 1 : 0);
        }
        if ($a['langCode'] !== $b['langCode']) {
            return $a['langCode'] === 'pt-pt' ? -1 : 1;
        }
        return $b['downloads'] <=> $a['downloads'];
    });

    return $results;
}

function openSubtitlesVttCachePath($fileId) {
    $dir = sys_get_temp_dir() . '/opensubtitles_vtt';
    if (!is_dir($dir)) {
        @mkdir($dir, 0755, true);
    }
    return $dir . '/' . (int) $fileId . '.vtt';
}

// SubRip and WebVTT differ in exactly three places that matter to a player:
// the required WEBVTT signature, "," as the decimal separator in timestamps,
// and stray CRs. Everything else (cue numbering, blank-line separation, the
// text itself) is already valid WebVTT.
function srtToVtt($text) {
    $text = preg_replace('/^\xEF\xBB\xBF/', '', $text);
    $text = str_replace("\r\n", "\n", $text);
    $text = str_replace("\r", "\n", $text);

    if (strncmp(ltrim($text), 'WEBVTT', 6) === 0) {
        return $text;
    }

    $text = preg_replace(
        '/(\d{2}:\d{2}:\d{2}),(\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}),(\d{3})/',
        '$1.$2 --> $3.$4',
        $text
    );

    return "WEBVTT\n\n" . ltrim($text);
}

// Resolves one OpenSubtitles file_id to WebVTT text, caching the result on
// disk forever afterwards.
//
// The caching is not an optimization, it is what makes this usable at all:
// the download endpoint is capped at 20 files/day for this account, and it
// hands back a temporary link rather than a stable one, so re-resolving the
// same subtitle on every playback would burn the entire day's quota on a
// handful of views. Returns false when the quota is spent, the token has
// expired, or the fetch fails - the caller serves an empty cue list rather
// than breaking playback over a missing subtitle.
function openSubtitlesFetchVtt($fileId) {
    global $openSubtitlesApiKey, $openSubtitlesApiToken;

    $cachePath = openSubtitlesVttCachePath($fileId);
    if (is_file($cachePath) && filesize($cachePath) > 0) {
        return (string) file_get_contents($cachePath);
    }

    if (empty($openSubtitlesApiKey) || empty($openSubtitlesApiToken)) {
        return false;
    }

    $headers = [
        'Api-Key: ' . $openSubtitlesApiKey,
        'Authorization: Bearer ' . $openSubtitlesApiToken,
        'Content-Type: application/json',
        'Accept: application/json',
        'User-Agent: tmdb-to-vod v1.0',
    ];

    $ch = curl_init('https://api.opensubtitles.com/api/v1/download');
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT => 15,
        CURLOPT_POST => true,
        CURLOPT_POSTFIELDS => json_encode(['file_id' => (int) $fileId]),
        CURLOPT_HTTPHEADER => $headers,
    ]);
    $response = curl_exec($ch);
    $status = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($response === false || $status !== 200) {
        return false;
    }

    $link = json_decode($response, true)['link'] ?? '';
    if ($link === '') {
        return false;
    }

    $ch = curl_init($link);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT => 20,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_HTTPHEADER => ['User-Agent: tmdb-to-vod v1.0'],
    ]);
    $body = curl_exec($ch);
    $status = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($body === false || $status !== 200 || trim((string) $body) === '') {
        return false;
    }

    $vtt = srtToVtt((string) $body);
    @file_put_contents($cachePath, $vtt);

    return $vtt;
}

// Segments/init files are cache data, not persistent state - regenerable at
// any time from the source URL - so they belong in RAM (tmpfs), not on the
// server's small SSD. /dev/shm is the standard RAM-backed tmpfs on Linux;
// fall back to the regular temp dir (disk) only on a system that doesn't
// have one (e.g. local dev on macOS), so nothing breaks outside production.
// Checked once per process and cached in a static, since it's a handful of
// filesystem calls that never change mid-request.
function getRamCacheDir() {
    static $dir = null;
    if ($dir !== null) {
        return $dir;
    }

    $shm = '/dev/shm';
    if (is_dir($shm) && is_writable($shm)) {
        $dir = $shm . '/subtitle_track_cache';
    } else {
        $dir = sys_get_temp_dir() . '/subtitle_track_cache';
    }
    if (!is_dir($dir)) {
        @mkdir($dir, 0755, true);
    }
    return $dir;
}

// How much cache space (bytes) a single source is allowed to hold, sized
// from its own bitrate rather than a flat number every title gets
// regardless of how much data one segment of it actually is. Calibrated so
// a ~90Mbps remux (a real title in this catalog: 1080p HEVC + TrueHD Atmos
// 7.1) lands around 120MB - enough to hold the segment a player is
// currently on plus roughly one buffered ahead, not the whole movie times
// over. A 480p file gets proportionally less; the floor keeps very-low-
// bitrate titles from being capped so tight that concurrent requests for
// the same segment can't share a cache hit, and the ceiling keeps one
// unusually high-bitrate title from crowding out every other stream
// sharing the same RAM cache.
function computeStreamCacheBudgetBytes($bitrateBps) {
    if ($bitrateBps <= 0) {
        $bitrateBps = 15_000_000; // Reasonable guess when nothing else is known.
    }
    $targetSeconds = 10.67; // ~1.3x the 8s segment length.
    $budget = ($bitrateBps / 8) * $targetSeconds;
    return (int) max(20 * 1024 * 1024, min($budget, 300 * 1024 * 1024));
}

// Keeps one source's cache subdirectory under its computed byte budget by
// deleting its oldest files first (by mtime), skipping whatever the caller
// just wrote (so a request never evicts its own freshly-cached output) and
// the init segment (tiny and reused by every segment of this source, so
// it's not worth ever evicting to make room). Called right after writing a
// new segment/init file, so the directory never grows past budget between
// requests instead of relying purely on the periodic sweep below.
function enforceStreamCacheBudget($videoDir, $budgetBytes, $justWrittenPath) {
    $entries = @scandir($videoDir);
    if ($entries === false) {
        return;
    }

    $files = [];
    $totalSize = 0;
    foreach ($entries as $entry) {
        // Init segments (video_init.mp4, audio_init_truehd.mp4,
        // audio_init_aac.mp4) are tiny and reused by every fragment of
        // their rendition, so they're never worth evicting to make room -
        // matched by substring rather than one exact name now that there's
        // more than one of them (one video-only, two audio-only: TrueHD and
        // an AAC stereo fallback for players/devices that can't decode
        // TrueHD-in-MP4, e.g. VLC's own 'mlpa' decoder gap).
        if ($entry === '.' || $entry === '..' || strpos($entry, 'init') !== false) {
            continue;
        }
        $path = $videoDir . '/' . $entry;
        if (!is_file($path) || $path === $justWrittenPath) {
            continue;
        }
        $size = @filesize($path);
        $mtime = @filemtime($path);
        if ($size === false || $mtime === false) {
            continue;
        }
        $files[] = ['path' => $path, 'size' => $size, 'mtime' => $mtime];
        $totalSize += $size;
    }

    if ($totalSize <= $budgetBytes) {
        return;
    }

    usort($files, function ($a, $b) {
        return $a['mtime'] <=> $b['mtime'];
    });

    foreach ($files as $file) {
        if ($totalSize <= $budgetBytes) {
            break;
        }
        if (@unlink($file['path'])) {
            $totalSize -= $file['size'];
        }
    }
}

// Periodic (caller decides how often - both segment scripts do this with
// low probability per request, same pattern as the old disk-cache pruning)
// cleanup of whole per-source cache subdirectories nobody has touched
// recently - i.e. playback that was abandoned or finished, not actively
// bounded by enforceStreamCacheBudget() above because no new request is
// coming in to trigger it. Unlike the old multi-hour disk TTL, RAM is
// precious enough that a few minutes of inactivity is treated as "done".
function sweepAbandonedStreamCaches($cacheRoot, $maxAgeSeconds = 300) {
    $entries = @scandir($cacheRoot);
    if ($entries === false) {
        return;
    }

    foreach ($entries as $entry) {
        if ($entry === '.' || $entry === '..') {
            continue;
        }
        $videoDir = $cacheRoot . '/' . $entry;
        if (!is_dir($videoDir)) {
            continue;
        }

        $newestMtime = 0;
        $files = @scandir($videoDir);
        if ($files === false) {
            continue;
        }
        foreach ($files as $file) {
            if ($file === '.' || $file === '..') {
                continue;
            }
            $mtime = @filemtime($videoDir . '/' . $file);
            if ($mtime !== false && $mtime > $newestMtime) {
                $newestMtime = $mtime;
            }
        }

        if ($newestMtime === 0 || (time() - $newestMtime) >= $maxAgeSeconds) {
            foreach ($files as $file) {
                if ($file !== '.' && $file !== '..') {
                    @unlink($videoDir . '/' . $file);
                }
            }
            @rmdir($videoDir);
        }
    }
}

// Maps ffprobe's color_transfer to the value HLS's VIDEO-RANGE attribute
// expects. Apple's AVFoundation (QuickTime, Safari, tvOS) is the strict
// case this matters for - without an explicit VIDEO-RANGE on
// #EXT-X-STREAM-INF it can default to treating PQ (HDR10/most Dolby Vision
// base layers) content as SDR, which renders as a washed-out, wrong-hue
// image rather than either failing cleanly or tone-mapping correctly.
function hlsVideoRangeFromColorTransfer($colorTransfer) {
    if ($colorTransfer === 'smpte2084') {
        return 'PQ';
    }
    if ($colorTransfer === 'arib-std-b67') {
        return 'HLG';
    }
    return 'SDR';
}

// Runs an ffmpeg fragmented-MP4 command that writes to a real (RAM-backed)
// file rather than a pipe - required for -movflags default_base_moof to
// write correct moof box sizes, since ffmpeg needs to seek back and fill
// them in once known, which a pipe can't do. Confirmed directly: the same
// command piped to stdout produces a moof with size=0 (spec-legal only for
// the last box in a stream, which this isn't - mdat and more always follow -
// so any correct demuxer, including every real player, rejects it as
// corrupt), while writing to a file produces the correct size and decodes
// cleanly.
//
// Waits for ffmpeg with a poll-and-timeout loop (not a blocking wait) so a
// client that disconnects mid-generation is noticed and cleaned up instead
// of leaving an abandoned process running to completion for nobody.
//
// Shared by the video-only and audio-only segment scripts, which differ
// only in which streams/codecs they map - $cmd is the full command line,
// already built by the caller, ending in $rawTmpPath as the output target.
//
// Returns ['fragment' => string, 'outcome' => null, 'stderr' => string] on
// success, or ['fragment' => false, 'outcome' => 'ffmpeg_start_failed'|
// 'client_aborted'|'ffmpeg_timeout'|'no_output_file'|'empty_output'] on
// failure. The init portion of ffmpeg's own throwaway output is discarded -
// only the fragment is returned, since every real init segment comes from a
// dedicated endpoint (subtitle_video_init.php / subtitle_audio_init.php)
// instead.
//
// $stderrCapturePath, when given, captures this invocation's stderr into its
// OWN file instead of the shared append-only debug log, and its content is
// both appended to the shared log (so nothing is lost for debugging) AND
// returned to the caller - needed so a caller that passed -debug_ts can read
// back this SPECIFIC request's own diagnostic output (the shared log is
// written by many concurrent requests at once, so there's no reliable way to
// isolate one request's lines out of it after the fact).
function runFragmentedMp4Segment($cmd, $rawTmpPath, $ffmpegLogPath, $stderrCapturePath = null) {
    $descriptorSpec = [
        0 => ['pipe', 'r'],
        1 => ['file', $ffmpegLogPath, 'a'],
        2 => $stderrCapturePath !== null ? ['file', $stderrCapturePath, 'w'] : ['file', $ffmpegLogPath, 'a'],
    ];

    $process = proc_open($cmd, $descriptorSpec, $pipes);
    if (!is_resource($process)) {
        return ['fragment' => false, 'outcome' => 'ffmpeg_start_failed'];
    }
    fclose($pipes[0]);

    // 60 iterations x 0.5s = 30s ceiling - generous margin over the ~2s a
    // segment typically takes even against a real remote source, without
    // letting a hung/stalled fetch tie up a process indefinitely.
    $aborted = false;
    $timedOut = true;
    for ($waited = 0; $waited < 60; $waited++) {
        $status = proc_get_status($process);
        if (!$status['running']) {
            $timedOut = false;
            break;
        }
        if (connection_aborted()) {
            $aborted = true;
            break;
        }
        usleep(500000);
    }

    $capturedStderr = '';
    if ($stderrCapturePath !== null && file_exists($stderrCapturePath)) {
        $capturedStderr = (string) file_get_contents($stderrCapturePath);
        @file_put_contents($ffmpegLogPath, $capturedStderr, FILE_APPEND);
        @unlink($stderrCapturePath);
    }

    if ($aborted || $timedOut) {
        proc_terminate($process);
        proc_close($process);
        @unlink($rawTmpPath);
        return ['fragment' => false, 'outcome' => $aborted ? 'client_aborted' : 'ffmpeg_timeout'];
    }

    proc_close($process);

    if (!file_exists($rawTmpPath)) {
        return ['fragment' => false, 'outcome' => 'no_output_file'];
    }

    $rawOutput = file_get_contents($rawTmpPath);
    @unlink($rawTmpPath);

    if ($rawOutput === false || strlen($rawOutput) < 8) {
        return ['fragment' => false, 'outcome' => 'empty_output'];
    }

    list($init, $fragment) = splitFmp4InitAndFragment($rawOutput);
    unset($rawOutput);

    // A bare moof+mdat fragment has no moov of its own, so it can't be
    // ffprobe'd in isolation the way a self-contained file could. A basic
    // size sanity check catches the failure modes that actually matter here
    // (ffmpeg dying early, an empty/truncated fragment) without needing to
    // reconstruct a temporary init+fragment file just to verify it.
    if (strlen($fragment) <= 4096) {
        return ['fragment' => false, 'outcome' => 'invalid_fragment'];
    }

    // Pulled from THIS invocation's own throwaway init header - see
    // extractMdhdTimescale() for why that's the only reliable source for it
    // (confirmed directly: assuming the source's own demuxer time_base was
    // fine for an MP4 source but wrong by a factor of 16 for an MKV one).
    $timescale = extractMdhdTimescale($init);

    return ['fragment' => $fragment, 'outcome' => null, 'stderr' => $capturedStderr, 'timescale' => $timescale];
}

// Reads the timescale (ticks per second) a fragmented-MP4 track's mdhd box
// declares - moov -> trak -> mdia -> mdhd. This is the ONLY reliable source
// for "what timescale will this segment's tfdt need to be expressed in" -
// confirmed directly that assuming it equals the SOURCE stream's own
// ffprobe-reported time_base (an earlier version of this codebase did) is
// wrong whenever the source is a Matroska/MKV file: ffprobe reports a
// generic container time_base of 1/1000 for EVERY stream in an MKV
// regardless of real codec rate, while ffmpeg's own MP4 muxer picks a real
// derived timescale when remuxing from it (measured directly: 1/16000 for
// h264 video, 1/48000 for DTS audio, on one real BluRay remux) - patching
// tfdt using the wrong scale doesn't just misalign one segment, it's off by
// a constant multiplicative factor throughout, which is what turned into
// the sustained multi-second discontinuities/audio-video desync/speed
// changes actually reported against a real MKV-sourced episode, while the
// same code worked correctly against an MP4 movie source (where source
// time_base and output timescale happen to coincide). Reading it straight
// from THIS invocation's own generated init header sidesteps the guesswork
// entirely - it's not a guess about what the muxer MIGHT pick, it's what it
// actually picked, for this exact ffmpeg invocation.
function extractMdhdTimescale($initBytes) {
    $len = strlen($initBytes);
    $moovs = findChildBoxes($initBytes, 'moov', 0, $len);
    if (empty($moovs)) {
        return null;
    }
    [$moovOffset, $moovSize] = $moovs[0];

    $traks = findChildBoxes($initBytes, 'trak', $moovOffset + 8, $moovOffset + $moovSize);
    if (empty($traks)) {
        return null;
    }
    [$trakOffset, $trakSize] = $traks[0];

    $mdias = findChildBoxes($initBytes, 'mdia', $trakOffset + 8, $trakOffset + $trakSize);
    if (empty($mdias)) {
        return null;
    }
    [$mdiaOffset, $mdiaSize] = $mdias[0];

    $mdhds = findChildBoxes($initBytes, 'mdhd', $mdiaOffset + 8, $mdiaOffset + $mdiaSize);
    if (empty($mdhds)) {
        return null;
    }
    [$mdhdOffset] = $mdhds[0];

    $version = ord(substr($initBytes, $mdhdOffset + 8, 1));
    // mdhd body: header(8) + version(1) + flags(3), then either
    // creation_time+modification_time as 64-bit each (version 1) or 32-bit
    // each (version 0), immediately followed by the 32-bit timescale.
    $timescaleOffset = $mdhdOffset + 12 + ($version === 1 ? 16 : 8);

    return unpack('N', substr($initBytes, $timescaleOffset, 4))[1];
}

// Confirmed directly (via -debug_ts on a real source): input-side -ss
// seeking with -c:v copy does NOT reliably land within a fraction of a
// second of the requested target the way it does for audio - it snaps back
// to whatever the nearest preceding keyframe is, and different torrent
// encodes of "the same" release can have very different, sometimes large
// (10+ second) keyframe intervals. Requesting -ss 24 on one real BluRay x264
// encode measured this way landed the actual first video packet at
// pts_time=13.89, a ~10 second gap - not the sub-frame difference an earlier,
// different encode of the same movie showed. Assuming nominal $start is
// close enough to the real landing point (as an earlier version of the tfdt
// patch did) writes a tfdt that's wrong by that same large, unpredictable
// gap - which a real player renders as the picture visibly jumping backward
// at that segment's boundary, recurring every segment, while audio (which
// doesn't have this keyframe constraint at all) stays perfectly in sync -
// exactly the "video glitches/goes back every 7-9 seconds, sound is fine"
// symptom this exists to fix.
//
// -debug_ts prints every demuxed packet's real timestamp to stderr before
// muxing touches it at all, so the SAME ffmpeg invocation that generates the
// segment can report its own true seek-landing point at zero extra network
// cost - no separate probe process needed. This pulls the very FIRST such
// line for the given stream type out of that invocation's own stderr.
function extractRealFragmentStartPtsTime($stderrText, $streamType) {
    if (preg_match('/\bdemuxer -> ist_index:\d+:\d+ type:' . preg_quote($streamType, '/') . ' pkt_pts:-?\d+ pkt_pts_time:(-?[0-9.]+)/', $stderrText, $m)) {
        return (float) $m[1];
    }
    return null;
}

// Builds a human-readable name for the "original audio" HLS rendition (e.g.
// "TrueHD Atmos 7.1", "DTS-HD MA 5.1", "AC3 5.1") from ffprobe's raw fields -
// used for #EXT-X-MEDIA's NAME attribute so the track picker in a player
// that exposes one shows something meaningful instead of a generic label,
// since this project serves many different releases with many different
// source audio codecs, not just TrueHD.
function buildAudioRenditionName($codecName, $channels, $channelLayout, $profile) {
    $codecLabels = [
        'truehd' => 'TrueHD',
        'eac3' => 'E-AC3',
        'ac3' => 'AC3',
        'dts' => 'DTS',
        'aac' => 'AAC',
        'flac' => 'FLAC',
        'opus' => 'Opus',
        'pcm_s16le' => 'PCM',
        'pcm_s24le' => 'PCM',
    ];
    $label = $codecLabels[$codecName] ?? strtoupper((string) $codecName);

    // ffprobe's DTS profile names distinguish plain DTS from the lossless
    // DTS-HD MA variant - worth surfacing since they're very different in
    // practice (lossy vs lossless).
    if ($codecName === 'dts' && stripos($profile, 'MA') !== false) {
        $label = 'DTS-HD MA';
    }
    if (stripos($profile, 'Atmos') !== false) {
        $label .= ' Atmos';
    }

    $channelLabel = $channelLayout !== '' ? $channelLayout : ($channels > 0 ? $channels . 'ch' : '');
    // Layout strings like "5.1(side)" carry a parenthetical that's just
    // noise for a track-picker label.
    $channelLabel = preg_replace('/\s*\(.*\)$/', '', $channelLabel);

    return trim($label . ($channelLabel !== '' ? ' ' . $channelLabel : ''));
}

// Builds ffmpeg -metadata args for title/date, shared by
// subtitle_video_init.php and subtitle_audio_init.php - metadata can only
// live in a moov box, which only the init segments have (fragments carry no
// container-level metadata of their own), so both init generators need this
// independently rather than it being set once somewhere upstream. Safe from
// shell injection regardless of what's in $title (quotes, spaces, etc.) -
// proc_open's array form passes each element as a literal argv entry, never
// through a shell.
function buildMp4MetadataArgs($title, $year, $encoder = '') {
    $args = [];
    if ($title !== '') {
        $args[] = '-metadata';
        $args[] = 'title=' . $title;
    }
    if ($year !== '') {
        $args[] = '-metadata';
        $args[] = 'date=' . $year;
    }
    if ($encoder !== '') {
        // ffmpeg's MP4 muxer maps this to the '©too' atom - what VLC and
        // most other players label "Encoded by" in their media info panel.
        $args[] = '-metadata';
        $args[] = 'encoder=' . $encoder;
    }
    return $args;
}

// Pulls the release-group tag off a scene/P2P-style release filename - e.g.
// ".../Black Widow 2021 1080p BluRay DV HDR10 x265 10bit-GeneMige.mkv"
// yields "GeneMige". That naming convention (title/tags, then a final
// hyphen-group with no spaces, right before the extension) is near-
// universal for these releases, but not guaranteed, so this returns '' on
// anything that doesn't clearly match rather than guessing - showing no
// "Encoded by" is a lot less confusing than showing a wrong one.
function extractReleaseGroupFromUrl($videoUrl) {
    $path = parse_url($videoUrl, PHP_URL_PATH);
    if ($path === null || $path === false) {
        return '';
    }
    $filename = urldecode(basename($path));
    if (preg_match('/-([A-Za-z0-9]+)\.[A-Za-z0-9]{2,4}$/', $filename, $m)) {
        return $m[1];
    }
    return '';
}

function curlGetSimple($url, $timeout = 15) {
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($ch, CURLOPT_TIMEOUT, $timeout);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/5.0');
    $response = curl_exec($ch);
    curl_close($ch);
    return $response;
}

// Starts an async duration probe (ffprobe reading just container metadata,
// not the whole file) and returns immediately - the caller can do other
// slow work (e.g. the AIOStreams subtitle lookup) before calling
// finishDurationProbe(), so the two run concurrently instead of back to
// back. Real duration is cached per source URL so repeat playlist loads
// don't reprobe at all.
function startDurationProbe($videoUrl, $ffprobePath) {
    // Bump whenever the shape of the cached result changes (new fields
    // added/removed) - otherwise a cache entry written under the OLD shape
    // keeps being served as-is for up to the full TTL, silently missing
    // whatever new field a caller now expects (this bit us directly: adding
    // width/height/colorTransfer/audio* fields without this left
    // subtitle_track_playlist.php reading them as empty from stale entries,
    // so RESOLUTION/VIDEO-RANGE quietly stopped appearing for any title
    // probed before the change, for up to 2 hours after deploy).
    $probeVersion = 3;

    $cacheFile = sys_get_temp_dir() . '/subtitle_track_duration_cache.json';
    $cacheKey = md5(stableCacheKeyForVideo($videoUrl) . '|v' . $probeVersion);

    $cache = [];
    if (file_exists($cacheFile)) {
        $decoded = json_decode((string) file_get_contents($cacheFile), true);
        if (is_array($decoded)) {
            $cache = $decoded;
        }
    }

    if (isset($cache[$cacheKey]) && (time() - $cache[$cacheKey]['time']) < 7200) {
        return ['cached' => $cache[$cacheKey]];
    }

    // bit_rate rides along with duration in the same probe (no extra network
    // round-trip) - it's what the RAM cache budget in
    // computeStreamCacheBudgetBytes() is sized from, so a high-bitrate
    // remux gets more cache headroom than a small 480p file automatically,
    // instead of every source getting the same fixed budget regardless of
    // how much data one segment of it actually holds. width/height/
    // color_transfer are what subtitle_track_playlist.php uses to add
    // RESOLUTION and VIDEO-RANGE to #EXT-X-STREAM-INF - without those,
    // strict HLS clients (Apple's AVFoundation - QuickTime, Safari, tvOS -
    // in particular) can fall back to assuming SDR for HDR10 (PQ) content,
    // which renders as a washed-out, wrong-hue image instead of failing
    // outright or tone-mapping correctly.
    // JSON, not the flat key=value format used elsewhere in this file -
    // needed here specifically because this probe (unlike the others) reads
    // fields from BOTH the video and audio streams at once, and JSON is what
    // keeps "width" from stream 0 unambiguous from an unrelated field on
    // stream 1 rather than everything collapsing into one flat, unordered
    // list of lines.
    // stream_tags=language,title rides along for the same reason bit_rate
    // does - no extra round trip - and is what lets the audio track actually
    // be CHOSEN by language instead of blindly taking 0:a:0. Real reports
    // that forced this: an "English" release of The Beekeeper whose first
    // audio track is Italian, and a Black Widow release whose first track is
    // Russian; both played in the wrong language while the playlist labelled
    // them English. See pickAudioStreamForLanguage().
    $probeCmd = [$ffprobePath, '-v', 'error', '-show_entries', 'format=duration,bit_rate:stream=index,codec_type,width,height,color_transfer,codec_name,channels,channel_layout,profile:stream_tags=language,title', '-of', 'json', $videoUrl];
    $descriptors = [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['file', '/dev/null', 'a']];
    $process = proc_open($probeCmd, $descriptors, $pipes);
    if (!is_resource($process)) {
        return ['cached' => false];
    }
    fclose($pipes[0]);
    stream_set_blocking($pipes[1], false);

    return ['cached' => null, 'process' => $process, 'pipes' => $pipes, 'cacheKey' => $cacheKey, 'cacheFile' => $cacheFile, 'videoUrl' => $videoUrl];
}

// Waits for (if needed) and returns ['duration' => float, 'bitRateBps' => int]
// from a handle started by startDurationProbe(), or false on failure. Safe
// to call immediately if the caller had no other work to interleave - it
// just blocks until ffprobe finishes, same as the old synchronous version
// did.
function finishDurationProbe($probe) {
    if ($probe['cached'] !== null) {
        return $probe['cached'] === false ? false : $probe['cached'];
    }

    $pipes = $probe['pipes'];
    $process = $probe['process'];

    $output = '';
    for ($waited = 0; $waited < 15; $waited++) {
        $read = [$pipes[1]];
        $write = null;
        $except = null;
        if (@stream_select($read, $write, $except, 1) > 0) {
            $output .= fread($pipes[1], 8192);
        }
        $status = proc_get_status($process);
        if (!$status['running'] && feof($pipes[1])) {
            break;
        }
    }
    fclose($pipes[1]);
    proc_terminate($process);
    proc_close($process);

    $decoded = json_decode(trim($output), true);
    if (!is_array($decoded)) {
        return false;
    }

    $duration = (float) ($decoded['format']['duration'] ?? 0);
    // ffprobe prints bit_rate as a numeric string, or omits/null's it
    // entirely for a container that doesn't carry one at all.
    $bitRateBps = (int) ($decoded['format']['bit_rate'] ?? 0);

    $width = 0;
    $height = 0;
    $colorTransfer = '';
    $audioCodecName = '';
    $audioChannels = 0;
    $audioChannelLayout = '';
    $audioProfile = '';
    // Every audio track, in ffmpeg's own 0:a:N order, so a caller can pick
    // one by language rather than being stuck with whichever happens to be
    // first in the file.
    $audioStreams = [];
    foreach ($decoded['streams'] ?? [] as $stream) {
        if (($stream['codec_type'] ?? '') === 'video' && $width === 0) {
            $width = (int) ($stream['width'] ?? 0);
            $height = (int) ($stream['height'] ?? 0);
            $colorTransfer = (string) ($stream['color_transfer'] ?? '');
        } elseif (($stream['codec_type'] ?? '') === 'audio') {
            if ($audioCodecName === '') {
                $audioCodecName = (string) ($stream['codec_name'] ?? '');
                $audioChannels = (int) ($stream['channels'] ?? 0);
                $audioChannelLayout = (string) ($stream['channel_layout'] ?? '');
                $audioProfile = (string) ($stream['profile'] ?? '');
            }
            $audioStreams[] = [
                'audioIndex' => count($audioStreams),
                'codecName' => (string) ($stream['codec_name'] ?? ''),
                'channels' => (int) ($stream['channels'] ?? 0),
                'channelLayout' => (string) ($stream['channel_layout'] ?? ''),
                'profile' => (string) ($stream['profile'] ?? ''),
                'language' => strtolower((string) ($stream['tags']['language'] ?? '')),
                'title' => (string) ($stream['tags']['title'] ?? ''),
            ];
        }
    }

    if ($duration <= 0) {
        return false;
    }

    // Some remuxes (this project deals with plenty of them) don't carry a
    // container-level bit_rate at all - ffprobe prints "N/A" for it, which
    // the regex above simply won't match, leaving bitRateBps at 0. Falling
    // back to a HEAD request's Content-Length gives a real per-title
    // estimate instead of falling through to computeStreamCacheBudgetBytes()'s
    // generic guess for every such file.
    if ($bitRateBps <= 0 && !empty($probe['videoUrl'])) {
        $ch = curl_init($probe['videoUrl']);
        curl_setopt($ch, CURLOPT_NOBODY, true);
        curl_setopt($ch, CURLOPT_HEADER, true);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_TIMEOUT, 10);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
        curl_exec($ch);
        $contentLength = (int) curl_getinfo($ch, CURLINFO_CONTENT_LENGTH_DOWNLOAD);
        curl_close($ch);
        if ($contentLength > 0) {
            $bitRateBps = (int) (($contentLength * 8) / $duration);
        }
    }

    $result = [
        'duration' => $duration,
        'bitRateBps' => $bitRateBps,
        'width' => $width,
        'height' => $height,
        'colorTransfer' => $colorTransfer,
        'audioCodecName' => $audioCodecName,
        'audioChannels' => $audioChannels,
        'audioChannelLayout' => $audioChannelLayout,
        'audioProfile' => $audioProfile,
        'audioStreams' => $audioStreams,
    ];

    $cache = [];
    if (file_exists($probe['cacheFile'])) {
        $decoded = json_decode((string) file_get_contents($probe['cacheFile']), true);
        if (is_array($decoded)) {
            $cache = $decoded;
        }
    }
    $cache[$probe['cacheKey']] = $result + ['time' => time()];
    @file_put_contents($probe['cacheFile'], json_encode($cache));

    return $result;
}

// Confirmed directly (probed the full keyframe list of a real 2h13m BluRay
// x264 source): keyframe spacing on real releases is NOT the tidy, regular
// 2-4s a naive fixed-length segmenter assumes - this file's gaps ranged from
// under 1s to over 10s, with roughly 1 in 10 keyframe gaps exceeding the 8s
// segment length subtitle_video_playlist.php/subtitle_audio_playlist.php
// used to cut on blindly. -c:v copy can only start a segment AT a keyframe
// (there's no decoding to trim mid-GOP), so any fixed nominal boundary that
// doesn't land on a real keyframe forces that segment to start from
// whichever keyframe came before it - which, when the gap is large, means
// the segment's first few seconds are content ALREADY shown by the previous
// segment (whose own -to cutoff reached right up to that same nominal
// boundary). That's a real, visible content repeat/rewind, not just a
// metadata problem - patching tfdt (see patchFirstFragmentTfdt()) fixes the
// container's timeline labeling but can't undo actual duplicated frames.
// The only real fix is cutting segments where the video's real keyframes
// actually are, the way every real HLS/CMAF packager (Shaka Packager,
// Bento4, Apple's own tools) already does - never blindly at a fixed
// interval.
//
function keyframeCacheFile() {
    return sys_get_temp_dir() . '/subtitle_track_keyframes_cache.json';
}

function keyframeCacheKey($videoUrl) {
    // Bump whenever computeKeyframeTimestamps()'s output shape/logic
    // changes - see startDurationProbe() for why this convention exists.
    $probeVersion = 1;
    return md5(stableCacheKeyForVideo($videoUrl) . '|v' . $probeVersion);
}

// Does the actual ffprobe work - reads packet-level keyframe flags only (no
// decoding). MP4's sample tables (stss = sync sample = keyframe list) live
// in the moov atom, so this is a metadata read, not a download of the whole
// file - but measured directly at 30-40s for a real 2+ hour movie anyway
// (the mov demuxer still has to walk the full sample table to answer a
// per-packet query, and -skip_frame nokey - which only emits keyframes -
// measured no faster, so the cost is inherent to the demuxer, not the
// output volume). That's far past what most HLS clients wait on a single
// playlist request before giving up - see getKeyframeTimestamps() for how
// callers avoid ever blocking on this directly.
function computeKeyframeTimestamps($videoUrl, $ffprobePath) {
    $probeCmd = [$ffprobePath, '-v', 'error', '-select_streams', 'v:0', '-show_entries', 'packet=pts_time,flags', '-of', 'csv=p=0', $videoUrl];
    $descriptors = [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['file', '/dev/null', 'a']];
    $process = proc_open($probeCmd, $descriptors, $pipes);
    if (!is_resource($process)) {
        return [];
    }
    fclose($pipes[0]);

    $keyframes = [];
    while (($line = fgets($pipes[1])) !== false) {
        // csv=p=0 rows look like "13.888875,K__" - only the 'K' flag (first
        // character) marks a real sync sample/keyframe; everything else is
        // a regular packet that can't be a segment start under -c:v copy.
        $parts = explode(',', trim($line));
        if (count($parts) === 2 && isset($parts[1][0]) && $parts[1][0] === 'K') {
            $keyframes[] = (float) $parts[0];
        }
    }
    fclose($pipes[1]);
    proc_close($process);

    sort($keyframes, SORT_NUMERIC);

    // Every real segmenter needs a keyframe at (or before) time 0 to anchor
    // the very first segment - if the source's first packet somehow isn't
    // flagged as one (malformed/unusual encode), forcing a synthetic 0.0
    // entry is still correct: -ss 0 needs no seek at all, so segment 0 never
    // depends on this list being accurate at that specific point anyway.
    if (empty($keyframes) || $keyframes[0] > 0.001) {
        array_unshift($keyframes, 0.0);
    }

    return $keyframes;
}

// Same probe as computeKeyframeTimestamps(), but time-boxed: reads whatever
// keyframes it can within $timeoutSeconds, then terminates the process and
// returns what it has instead of waiting for the full 30-40s scan. Confirmed
// directly this demuxer processes a real movie at roughly 200x real-time
// (a 2h24m file's full scan took ~43s), so even a short bound like 5s
// typically covers a good 15-20+ minutes of real content - far more of the
// movie than most viewers reach before this source's background probe (see
// scheduleKeyframeProbe()) has had a chance to finish and warm the cache
// properly. Used to give a COLD-cache playlist request something much
// better than the plain fixed-length fallback without making it wait
// anywhere near as long as the full probe - see getKeyframeTimestampsForResponse()
// for how the two combine.
function computeKeyframeTimestampsBounded($videoUrl, $ffprobePath, $timeoutSeconds) {
    $probeCmd = [$ffprobePath, '-v', 'error', '-select_streams', 'v:0', '-show_entries', 'packet=pts_time,flags', '-of', 'csv=p=0', $videoUrl];
    $descriptors = [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['file', '/dev/null', 'a']];
    $process = proc_open($probeCmd, $descriptors, $pipes);
    if (!is_resource($process)) {
        return [];
    }
    fclose($pipes[0]);
    stream_set_blocking($pipes[1], false);

    $keyframes = [];
    $buffer = '';
    $deadline = microtime(true) + $timeoutSeconds;

    while (microtime(true) < $deadline) {
        $status = proc_get_status($process);
        $read = [$pipes[1]];
        $write = null;
        $except = null;
        $remaining = max(0, $deadline - microtime(true));
        $usec = (int) min(200000, $remaining * 1000000);
        if (@stream_select($read, $write, $except, 0, $usec) > 0) {
            $chunk = fread($pipes[1], 65536);
            if ($chunk !== false && $chunk !== '') {
                $buffer .= $chunk;
                while (($pos = strpos($buffer, "\n")) !== false) {
                    $line = substr($buffer, 0, $pos);
                    $buffer = substr($buffer, $pos + 1);
                    $parts = explode(',', trim($line));
                    if (count($parts) === 2 && isset($parts[1][0]) && $parts[1][0] === 'K') {
                        $keyframes[] = (float) $parts[0];
                    }
                }
            }
        }
        if (!$status['running']) {
            break;
        }
    }

    $status = proc_get_status($process);
    if ($status['running']) {
        proc_terminate($process);
    }
    fclose($pipes[1]);
    proc_close($process);

    sort($keyframes, SORT_NUMERIC);
    if (empty($keyframes) || $keyframes[0] > 0.001) {
        array_unshift($keyframes, 0.0);
    }

    return $keyframes;
}

// Cache-first entry point for a PLAYLIST RESPONSE that needs keyframe data
// right now and can't wait through the full 30-40s probe. Returns
// [$keyframeTimes, $needsBackgroundProbe]:
// - Warm cache: the full list, $needsBackgroundProbe = false.
// - Cold cache: a bounded partial probe result (better than nothing, still
//   fast enough not to time out a real client), $needsBackgroundProbe =
//   true so the caller knows to follow up with scheduleKeyframeProbe()
//   AFTER sending its response, to complete and cache the full list for
//   next time - see the big comment on scheduleKeyframeProbe() for why
//   that step can never happen before the response goes out.
function getKeyframeTimestampsForResponse($videoUrl, $ffprobePath, $boundedSeconds = 5.0) {
    $keyframeTimes = getKeyframeTimestamps($videoUrl, $ffprobePath);
    if (!empty($keyframeTimes)) {
        return [$keyframeTimes, false];
    }

    return [computeKeyframeTimestampsBounded($videoUrl, $ffprobePath, $boundedSeconds), true];
}

function writeKeyframeCacheEntry($videoUrl, $keyframes) {
    $cacheFile = keyframeCacheFile();
    $cache = [];
    if (file_exists($cacheFile)) {
        $decoded = json_decode((string) file_get_contents($cacheFile), true);
        if (is_array($decoded)) {
            $cache = $decoded;
        }
    }
    $cache[keyframeCacheKey($videoUrl)] = ['keyframes' => $keyframes, 'time' => time()];
    @file_put_contents($cacheFile, json_encode($cache));
}

// NEVER runs the real probe before the response is sent - confirmed
// directly that doing so was the cause of a real, serious regression: a
// brand-new (never-before-cached) source's FIRST video/audio playlist
// request took 30-40s to respond while computeKeyframeTimestamps() ran
// synchronously, and that's long enough for a real player/HTTP client's own
// request timeout to fire first - the movie "never loads" from the
// viewer's side even though the server would eventually have answered.
// Keyframe-aligned segmentation is worth a lot (see
// buildKeyframeAlignedSegments()) but not at the cost of the playlist never
// being served at all.
//
// This is a pure cache read - a miss returns [] immediately, letting
// buildKeyframeAlignedSegments()'s existing fixed-length fallback take over
// for THIS request (worse - can repeat a little content at a boundary on a
// large-GOP source - but real and immediate). The caller is responsible for
// following up with scheduleKeyframeProbe() AFTER it has already sent its
// response (see that function for why), so that by the time the SAME
// viewer resumes/reloads, or the next viewer requests this title, the cache
// is warm and they get the fully keyframe-precise version instead.
//
// (An earlier version of this function tried to kick off the real probe as
// a detached background process - `exec('... &')` - right here, before
// responding. Confirmed directly that doesn't survive on this host: even a
// plain `nohup ... & disown` shelled out from PHP-FPM got killed the moment
// the request finished, so the "background" work never actually completed.
// fastcgi_finish_request(), which the caller uses instead, is the
// SAPI-level way to keep a worker process itself running past the point
// the client's response was flushed - reliable because it isn't relying on
// a child process surviving its parent's process group at all.)
function getKeyframeTimestamps($videoUrl, $ffprobePath) {
    $cacheFile = keyframeCacheFile();
    $cacheKey = keyframeCacheKey($videoUrl);

    if (file_exists($cacheFile)) {
        $decoded = json_decode((string) file_get_contents($cacheFile), true);
        if (is_array($decoded) && isset($decoded[$cacheKey]) && (time() - $decoded[$cacheKey]['time']) < 7200) {
            return $decoded[$cacheKey]['keyframes'];
        }
    }

    return [];
}

// Call AFTER the response has already been sent to the client (immediately
// following fastcgi_finish_request(), or as a fallback on a SAPI where
// that's unavailable - see below) whenever getKeyframeTimestamps() returned
// an empty/stale result for this source. Runs the real (slow) probe and
// writes it to cache so the NEXT request for this source gets the
// keyframe-precise segmentation - never the current one, which has already
// committed to the fixed-length fallback for its own response.
//
// A short-TTL lock file (much shorter than the cache's own 2-hour TTL) is
// what keeps the video AND audio playlist requests for the same just-gone-
// cold source - a real player fetches both within moments of each other -
// from each independently re-running this same 30-40s probe.
//
// On a SAPI without fastcgi_finish_request() (plain CLI, some non-FPM
// setups), this still runs synchronously before the calling script exits -
// slower for that one edge case, but correct, and every real deployment of
// this project runs under PHP-FPM anyway.
function scheduleKeyframeProbe($videoUrl, $ffprobePath) {
    $cacheKey = keyframeCacheKey($videoUrl);
    $lockFile = sys_get_temp_dir() . '/subtitle_track_keyframes_lock_' . $cacheKey . '.lock';
    if (file_exists($lockFile) && (time() - (int) @filemtime($lockFile)) < 120) {
        return;
    }
    @touch($lockFile);

    $keyframes = computeKeyframeTimestamps($videoUrl, $ffprobePath);
    if (!empty($keyframes)) {
        writeKeyframeCacheEntry($videoUrl, $keyframes);
    }
}

// Turns a sorted keyframe list into actual (start, length) segment pairs
// targeting roughly $targetSegmentLength each, but ALWAYS cutting exactly on
// a real keyframe - never in between. For each segment, picks the keyframe
// closest to (without exceeding) the target end; if the next available
// keyframe is already past the target (a GOP longer than the target itself -
// confirmed to happen on real sources, see getKeyframeTimestamps()), that
// keyframe is used anyway and the segment simply runs a bit long, since
// there's no earlier valid cut point under stream copy. Falls back to plain
// fixed-length segments if no keyframe list is available (e.g. probe
// failed) - worse (may repeat content at a boundary) but still playable,
// same as the pre-keyframe-aware behavior.
//
// The keyframe list is allowed to be PARTIAL - covering only the opening
// portion of the file, not all the way to $duration. That's not a
// malformed-input edge case to guard against defensively; it's an expected,
// everyday input shape (see computeKeyframeTimestampsBounded() - a
// deliberately time-boxed probe used so a brand-new source's first playlist
// request doesn't have to wait through the full 30-40s scan just to
// respond). Once the list runs dry noticeably before $duration, this
// switches to plain fixed-length stepping for the remainder - the same
// fallback quality as a source with no keyframe data at all, but only for
// the tail actually left unprobed, not the whole file. Getting this wrong
// (treating "list ran out" as "reached the real end of the file") would
// silently turn everything after the last known keyframe into ONE segment
// spanning the rest of the movie - confirmed directly as a real bug this
// exact function had before this comment was written.
function buildKeyframeAlignedSegments($keyframeTimes, $duration, $targetSegmentLength = 8) {
    if (empty($keyframeTimes)) {
        $segments = [];
        $numSegments = (int) ceil($duration / $targetSegmentLength);
        for ($i = 0; $i < $numSegments; $i++) {
            $start = $i * $targetSegmentLength;
            $segments[] = [$start, min($targetSegmentLength, $duration - $start)];
        }
        return $segments;
    }

    $segments = [];
    $current = 0.0;
    $count = count($keyframeTimes);
    $idx = 0;

    // Advance past any keyframes at/before 0 (there should be exactly the
    // one synthetic-or-real one at 0.0 itself).
    while ($idx < $count && $keyframeTimes[$idx] <= $current + 0.0001) {
        $idx++;
    }

    while ($current < $duration - 0.05) {
        // The list has run dry with real content still left uncovered - a
        // partial/bounded probe result, not a genuine end-of-file. Only a
        // small remaining tail (within about one target segment length of
        // $duration) is trusted as "this really is the end of the file";
        // anything larger switches to plain fixed-length stepping instead
        // of folding the entire unprobed remainder into one segment.
        if ($idx >= $count && ($duration - $current) > $targetSegmentLength * 1.5) {
            $end = min($current + $targetSegmentLength, $duration);
            $segments[] = [$current, $end - $current];
            $current = $end;
            continue;
        }

        $target = $current + $targetSegmentLength;
        $chosen = null;

        // Keep advancing while the NEXT keyframe is still within the target
        // window - $idx ends up at the first keyframe strictly beyond it.
        while ($idx < $count && $keyframeTimes[$idx] <= $target) {
            $chosen = $keyframeTimes[$idx];
            $idx++;
        }

        // No keyframe fell within the window at all - the current GOP
        // outlasts the target length, so the next real keyframe (however
        // far away) is the only valid place left to cut.
        if ($chosen === null) {
            if ($idx < $count) {
                $chosen = $keyframeTimes[$idx];
                $idx++;
            } else {
                $chosen = $duration;
            }
        }

        $end = min($chosen, $duration);
        if ($end <= $current) {
            // Guards against a malformed/duplicate keyframe list producing a
            // zero-or-negative-length segment - just reach the end instead
            // of looping forever.
            $end = $duration;
        }

        // Never emit a segment shorter than this - confirmed directly as a
        // real, reproducible bug: when two real keyframes land very close
        // together (here, the file's very first two keyframes were 0.083s
        // apart), the segment between them covers only 1-2 frames, and the
        // resulting fragment can come back small enough (well under 4KB) to
        // trip runFragmentedMp4Segment()'s "did ffmpeg actually produce
        // something real" sanity check - which exists to catch genuine
        // failures (ffmpeg dying, an empty response), not correctly-tiny
        // output, but can't tell the two apart from size alone. That
        // segment then 502s on every request for it, and since it's
        // segment 0 for a real title, the whole video/audio/subtitle
        // playlist fails to ever start - the movie "doesn't open" at all.
        // Merging forward into the next keyframe (or, if none give enough
        // length, straight to $duration) fixes it at the source: no segment
        // this pathologically short ever gets generated in the first place.
        $minSegmentLength = 1.0;
        while (($end - $current) < $minSegmentLength && $end < $duration) {
            if ($idx < $count) {
                $end = min($keyframeTimes[$idx], $duration);
                $idx++;
            } else {
                $end = $duration;
            }
        }

        $segments[] = [$current, $end - $current];
        $current = $end;
    }

    return $segments;
}

// Synchronous convenience wrapper for callers with no other work to
// interleave. Returns the duration in seconds, or false on failure - use
// getSourceDurationAndBitrate() instead when the bitrate is also needed.
function getSourceDuration($videoUrl, $ffprobePath) {
    $result = finishDurationProbe(startDurationProbe($videoUrl, $ffprobePath));
    return $result === false ? false : $result['duration'];
}

// Same probe, exposing the bitrate too - used to size the RAM cache budget
// per source (see computeStreamCacheBudgetBytes()).
function getSourceDurationAndBitrate($videoUrl, $ffprobePath) {
    return finishDurationProbe(startDurationProbe($videoUrl, $ffprobePath));
}

// The value handed to ffmpeg's -ss is deliberately NOT exactly $start -
// confirmed directly on a real BluRay MKV rip that landing precisely ON a
// keyframe's own timestamp is unreliable for -ss against Matroska sources:
// -ss values from a few milliseconds up to about 0.2s past the exact same
// keyframe all silently landed at the file's first keyframe (pts 0) instead
// of the intended one, while anything past roughly 0.2s landed correctly -
// an ffmpeg/Matroska seek-index quirk, not anything wrong with which
// keyframe was chosen. A small fixed margin comfortably clears that dead
// zone; it doesn't cost any real content because -c:v copy can only ever
// start a segment AT a keyframe regardless of the exact -ss value, so
// asking to land a bit past one still lands ON it, just via an approach
// distance the seek algorithm can resolve reliably - and the real absolute
// landing point is measured afterward anyway (see
// extractRealFragmentStartPtsTime()), so this only affects how reliably the
// intended keyframe is reached, never what timestamp ends up in the patched
// tfdt. Segment 0 needs no margin - -ss 0 is never ambiguous.
function seekTargetWithMargin($start) {
    return $start > 0 ? $start + 0.25 : 0;
}

// Tests whether an input-side -ss seek to $target (the SAME mechanism the
// real segment scripts use, no special recovery flags, including the same
// seekTargetWithMargin() clearance) actually lands near where it was asked
// to, using -copyts so the reported pts_time reflects the real source
// position instead of resetting near zero. Shared by isSeekReliable()'s two
// test points - see that function for why more than one point turned out to
// be necessary.
//
// Does NOT mux the seeked packets into any container - -f null discards
// them entirely, and the real landing pts_time is read straight out of
// -debug_ts's own stderr trace (the same technique
// extractRealFragmentStartPtsTime() already uses for the real segment
// scripts) instead of muxing to an intermediate file and re-probing it.
//
// Two earlier versions of this function both muxed to an intermediate file
// first, and BOTH turned out to have their own format-specific way of
// silently producing no readable output for a real AV1 source despite the
// seek itself working correctly:
// - MPEG-TS: ffmpeg muxes AV1 into it only as an unrecognized "private data
//   stream" (its own warning, verbatim) - ffprobe then reads back precisely
//   zero frames from it.
// - Plain (non-fragmented) MP4 with -copyts + -to: confirmed directly that
//   packets kept flowing through the demuxer (visible in -debug_ts) far
//   past where the seek landed, yet NONE of them ever reached the muxer -
//   "Output file is empty, nothing was encoded" - a separate AV1-specific
//   muxing gap, not a seek problem.
// Both failures were then indistinguishable from a genuinely broken seek
// index, and got the same fallback (a plain redirect, skipping HLS - and
// with it the subtitle track - entirely) meant for actually-corrupted
// sources. Reading the demuxer's own timestamp trace directly sidesteps
// the entire category of "can this codec even be muxed into the test
// format" bugs, since nothing gets muxed at all.
function testSeekLandsNear($target, $videoUrl, $ffmpegPath, $ffprobePath) {
    $probeCmd = [$ffmpegPath, '-y', '-debug_ts', '-copyts', '-ss', (string) seekTargetWithMargin($target), '-i', $videoUrl, '-to', (string) ($target + 10), '-map', '0:v:0', '-c:v', 'copy', '-f', 'null', '-'];
    $descriptors = [0 => ['pipe', 'r'], 1 => ['file', '/dev/null', 'a'], 2 => ['pipe', 'w']];
    $process = proc_open($probeCmd, $descriptors, $pipes);

    if (!is_resource($process)) {
        return false;
    }

    fclose($pipes[0]);
    $stderr = stream_get_contents($pipes[2]);
    fclose($pipes[2]);
    proc_close($process);

    $actualPts = extractRealFragmentStartPtsTime((string) $stderr, 'video');

    // Generous tolerance - keyframe snapping alone can legitimately land
    // several seconds before the requested target. This is about catching
    // "landed nowhere near what was asked for", not demanding exact
    // precision.
    return $actualPts !== null && $actualPts > 0 && abs($actualPts - $target) < 30;
}

// Some releases ship an MKV whose seek index is internally corrupted or
// incomplete - ffmpeg's own diagnosis for the classic case is literally
// "File is broken, keyframes not correctly marked!". For those files, an
// input-side -ss seek (exactly what the real segment scripts use) silently
// lands at roughly the same position regardless of the requested target,
// instead of erroring. The result: every segment ends up containing
// near-identical/overlapping content instead of continuing from the
// previous one - exactly the kind of jarring discontinuity that can crash a
// player right at the first segment boundary.
//
// Testing only ONE point well into the file (this function's original
// design) turned out to have a real, confirmed gap: a genuine Blu-ray MKV
// rip whose seek index covered the rest of the file perfectly (a seek to
// 1109s - past the 30%-of-duration test point - landed within a second of
// its target) still had -ss silently return pts=0 for EVERY position in
// roughly the first 10-20 seconds (confirmed directly: -ss 10 landed at 0,
// same as -ss 10.01, ruling out a formatting fluke). A check that only ever
// samples deep into the file can never see that - and HLS segmentation
// needs early-file seeks just as much as late ones (segment 1 starts
// wherever segment 0 ends, often well under 20s in). So this now tests TWO
// points - the original deep one, plus a fixed early one past typical
// intro/logo sequences but still inside where segment 1 or 2 would start -
// and requires BOTH to land correctly before trusting the source for HLS.
function isSeekReliable($videoUrl, $duration, $ffmpegPath, $ffprobePath) {
    // Bump this whenever the check's logic changes, so a code update can't
    // keep serving a stale verdict computed by the old (possibly buggy)
    // logic for up to the full cache TTL - it just naturally misses once and
    // recomputes under the new key instead.
    $checkVersion = 6;

    $cacheFile = sys_get_temp_dir() . '/subtitle_track_seek_check_cache.json';
    $cacheKey = md5(stableCacheKeyForVideo($videoUrl) . '|v' . $checkVersion);

    $cache = [];
    if (file_exists($cacheFile)) {
        $decoded = json_decode((string) file_get_contents($cacheFile), true);
        if (is_array($decoded)) {
            $cache = $decoded;
        }
    }

    if (isset($cache[$cacheKey]) && (time() - $cache[$cacheKey]['time']) < 7200) {
        return $cache[$cacheKey]['reliable'];
    }

    // Well past any intro/logo sequence, and proportionally into the file so
    // a long movie's index (if broken) doesn't get a pass just because the
    // test point happened to be early.
    $lateTarget = max(60, $duration * 0.3);
    $reliable = testSeekLandsNear($lateTarget, $videoUrl, $ffmpegPath, $ffprobePath);

    // Only worth the extra probe if the source is long enough for this
    // early point to be meaningfully distinct from the late one already
    // tested, and short files aren't where this failure mode has been seen
    // anyway.
    if ($reliable && $duration > 60) {
        $earlyTarget = 15.0;
        $reliable = testSeekLandsNear($earlyTarget, $videoUrl, $ffmpegPath, $ffprobePath);
    }

    $cache[$cacheKey] = ['reliable' => $reliable, 'time' => time()];
    @file_put_contents($cacheFile, json_encode($cache));

    return $reliable;
}
